"""add_job_id_support_to_files

Revision ID: 81a53520953b
Revises: be17e83e2941
Create Date: 2025-07-24 18:01:09.260695

"""
from typing import Sequence, Union
import uuid
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a53520953b'
down_revision: Union[str, Sequence[str], None] = 'be17e83e2941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Make conversation_id nullable to support job files
    op.alter_column('files', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Add job_id column for job files
    op.add_column('files', sa.Column('job_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_job_id'), 'files', ['job_id'], unique=False)
    # ### end Alembic commands ###
    
    # Add conversations category
    category_id = str(uuid.uuid4())
    current_time = datetime.utcnow().isoformat()
    op.execute(
        f"""
        INSERT INTO categories (id, name, description, created_at, updated_at, is_deleted)
        VALUES ('{category_id}', 'conversations', 'Category for conversation-related files', 
                '{current_time}', '{current_time}', false)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # First, set category_id to NULL for files that reference the conversations category
    op.execute("UPDATE files SET category_id = NULL WHERE category_id = (SELECT id FROM categories WHERE name = 'conversations')")
    
    # Remove conversations category
    op.execute("DELETE FROM categories WHERE name = 'conversations'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove job_id column
    op.drop_index(op.f('ix_files_job_id'), table_name='files')
    op.drop_column('files', 'job_id')
    
    # Make conversation_id non-nullable again
    op.alter_column('files', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
